run:
  timeout: 5m

linters:
  disable-all: true
  enable:
    - govet
    - staticcheck
    - errcheck
    - gosimple
    - ineffassign
    - unused
    - gofmt
    - goimports
    - revive

linters-settings:
  govet:
    enable-all: true
  revive:
    rules:
      - name: package-comments
      - name: error-strings
      - name: unreachable-code

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
