// SPDX-License-Identifier: Apache-2.0

// T-1302 AC2: table-driven decode test against T-1301's real pcap corpus
// (testdata/captures/, generated byte-deterministically by
// internal/capturemock.GenerateCorpus) — one case per protocol, plus the
// corpus's own truncated.pcap fixture for the "corrupt/truncated sample
// decodes defensively" requirement.
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { decodePcap } from "./CaptureDecoder";

const CORPUS_DIR = join(__dirname, "../../../testdata/captures");

function loadPcap(name: string): ArrayBuffer {
  const buf = readFileSync(join(CORPUS_DIR, name));
  return buf.buffer.slice(buf.byteOffset, buf.byteOffset + buf.byteLength);
}

describe("decodePcap", () => {
  it("decodes arp.pcap to an ARP request", () => {
    const result = decodePcap(loadPcap("arp.pcap"));
    expect(result.headerValid).toBe(true);
    expect(result.truncatedTail).toBe(false);
    expect(result.packets).toHaveLength(1);
    const [pkt] = result.packets;
    if (!pkt) throw new Error("expected a decoded packet");
    expect(pkt.truncated).toBe(false);
    expect(pkt.layers.map((l) => l.name)).toEqual(["Ethernet", "ARP"]);
    const arp = pkt.layers.find((l) => l.name === "ARP");
    expect(arp?.fields.operation).toBe("request");
    expect(arp?.fields.senderIp).toBe("10.0.0.1");
    expect(arp?.fields.targetIp).toBe("10.0.0.2");
    expect(pkt.summary).toContain("who-has 10.0.0.2");
    expect(pkt.summary).toContain("tell 10.0.0.1");
  });

  it("decodes icmp.pcap to an ICMP echo request", () => {
    const result = decodePcap(loadPcap("icmp.pcap"));
    expect(result.packets).toHaveLength(1);
    const [pkt] = result.packets;
    if (!pkt) throw new Error("expected a decoded packet");
    expect(pkt.layers.map((l) => l.name)).toEqual(["Ethernet", "IPv4", "ICMP"]);
    const ip = pkt.layers.find((l) => l.name === "IPv4");
    expect(ip?.fields.src).toBe("10.0.0.1");
    expect(ip?.fields.dst).toBe("10.0.0.2");
    expect(ip?.fields.protocol).toBe("ICMP");
    const icmp = pkt.layers.find((l) => l.name === "ICMP");
    expect(icmp?.fields.type).toBe("echo request");
    expect(icmp?.fields.id).toBe("1");
    expect(icmp?.fields.seq).toBe("1");
    expect(pkt.summary).toContain("echo request");
  });

  it("decodes tcp.pcap to a TCP SYN segment", () => {
    const result = decodePcap(loadPcap("tcp.pcap"));
    expect(result.packets).toHaveLength(1);
    const [pkt] = result.packets;
    if (!pkt) throw new Error("expected a decoded packet");
    expect(pkt.layers.map((l) => l.name)).toEqual(["Ethernet", "IPv4", "TCP"]);
    const tcp = pkt.layers.find((l) => l.name === "TCP");
    expect(tcp?.fields.srcPort).toBe("51000");
    expect(tcp?.fields.dstPort).toBe("443");
    expect(tcp?.fields.flags).toBe("SYN");
    expect(pkt.summary).toContain("51000");
    expect(pkt.summary).toContain("443");
    expect(pkt.summary).toContain("SYN");
  });

  it("decodes udp.pcap to a plain UDP datagram", () => {
    const result = decodePcap(loadPcap("udp.pcap"));
    expect(result.packets).toHaveLength(1);
    const [pkt] = result.packets;
    if (!pkt) throw new Error("expected a decoded packet");
    expect(pkt.layers.map((l) => l.name)).toEqual(["Ethernet", "IPv4", "UDP"]);
    const udp = pkt.layers.find((l) => l.name === "UDP");
    expect(udp?.fields.srcPort).toBe("40000");
    expect(udp?.fields.dstPort).toBe("9999");
  });

  it("decodes dns.pcap to a DNS query for vnprox.local", () => {
    const result = decodePcap(loadPcap("dns.pcap"));
    expect(result.packets).toHaveLength(1);
    const [pkt] = result.packets;
    if (!pkt) throw new Error("expected a decoded packet");
    expect(pkt.layers.map((l) => l.name)).toEqual(["Ethernet", "IPv4", "UDP", "DNS"]);
    const dns = pkt.layers.find((l) => l.name === "DNS");
    expect(dns?.fields.type).toBe("query");
    expect(dns?.fields.name).toBe("vnprox.local");
    expect(pkt.summary).toContain("vnprox.local");
  });

  it("decodes dhcp.pcap to a DHCP DISCOVER", () => {
    const result = decodePcap(loadPcap("dhcp.pcap"));
    expect(result.packets).toHaveLength(1);
    const [pkt] = result.packets;
    if (!pkt) throw new Error("expected a decoded packet");
    expect(pkt.layers.map((l) => l.name)).toEqual(["Ethernet", "IPv4", "UDP", "DHCP"]);
    const dhcp = pkt.layers.find((l) => l.name === "DHCP");
    expect(dhcp?.fields.messageType).toBe("DISCOVER");
    expect(pkt.summary).toContain("DISCOVER");
  });

  it("decodes vlan.pcap to a VLAN-tagged TCP segment", () => {
    const result = decodePcap(loadPcap("vlan.pcap"));
    expect(result.packets).toHaveLength(1);
    const [pkt] = result.packets;
    if (!pkt) throw new Error("expected a decoded packet");
    expect(pkt.layers.map((l) => l.name)).toEqual(["Ethernet", "VLAN", "IPv4", "TCP"]);
    const vlan = pkt.layers.find((l) => l.name === "VLAN");
    expect(vlan?.fields.vid).toBe("100");
    const tcp = pkt.layers.find((l) => l.name === "TCP");
    expect(tcp?.fields.dstPort).toBe("80");
  });

  it("decodes all-protocols.pcap to every protocol in order", () => {
    const result = decodePcap(loadPcap("all-protocols.pcap"));
    expect(result.headerValid).toBe(true);
    expect(result.truncatedTail).toBe(false);
    expect(result.packets).toHaveLength(7);
    const topLayers = result.packets.map((p) => p.layers[p.layers.length - 1]?.name);
    expect(topLayers).toEqual(["ARP", "ICMP", "TCP", "UDP", "DNS", "DHCP", "TCP"]);
    // The 7th packet (VLAN-tagged TCP) is the one with a VLAN layer.
    const vlanPkt = result.packets.at(6);
    if (!vlanPkt) throw new Error("expected a 7th decoded packet");
    expect(vlanPkt.layers.map((l) => l.name)).toEqual(["Ethernet", "VLAN", "IPv4", "TCP"]);
  });

  it("decodes truncated.pcap defensively: partial result, no crash", () => {
    const result = decodePcap(loadPcap("truncated.pcap"));
    expect(result.headerValid).toBe(true);
    // The first (complete) packet decodes fully; the second record's
    // declared length runs past the end of the file, so the loop stops
    // there rather than throwing or fabricating a packet from partial bytes.
    expect(result.packets).toHaveLength(1);
    const [firstPkt] = result.packets;
    if (!firstPkt) throw new Error("expected a decoded packet");
    expect(firstPkt.summary).toContain("echo request");
    expect(result.truncatedTail).toBe(true);
  });

  it("never throws on a bad global header", () => {
    const garbage = new Uint8Array([1, 2, 3, 4]).buffer;
    const result = decodePcap(garbage);
    expect(result.headerValid).toBe(false);
    expect(result.packets).toEqual([]);
  });

  it("never throws on an empty buffer", () => {
    const result = decodePcap(new ArrayBuffer(0));
    expect(result.headerValid).toBe(false);
    expect(result.packets).toEqual([]);
  });
});
