// SPDX-License-Identifier: Apache-2.0

// hub_registry_test.go drives T-2803's acceptance criteria through the *whole*
// real stack, with no double anywhere on the path: a signed index and artifact
// tree generated by internal/hubreg (the same code `vnproxctl hub index`
// runs), served over an httptest static file server, fetched by the real,
// unmodified internal/hub client with the T-2803 gate on its existing
// WithHTTPClient seam, installed through the real POST /hub/install handler
// and T-1107's real verify/trust/save path.
//
// The narrow unit tests live in internal/hubreg; these exist because AC2 and
// AC3 are claims about what an *operator's daemon* does, and a claim about the
// daemon has to be asserted at the daemon's own boundary.

package api

import (
	"crypto/ed25519"
	"encoding/json"
	"errors"
	"net/http"
	"net/http/httptest"
	"testing"

	"github.com/bgovanlu/vnprox/internal/blueprint"
	"github.com/bgovanlu/vnprox/internal/hub"
	"github.com/bgovanlu/vnprox/internal/hubreg"
)

// registryHosting is the static hosting a published registry is: index.json
// plus a tree of artifact files, both produced by hubreg itself.
//
//nolint:govet // fieldalignment: a test fixture; field order tells the fixture's story, not packing.
type registryHosting struct {
	t         *testing.T
	srv       *httptest.Server
	indexKey  ed25519.PrivateKey
	indexFP   string
	doc       hubreg.Document
	artifacts map[string][]byte
	calls     int
}

func newRegistryHosting(t *testing.T) *registryHosting {
	t.Helper()
	pub, priv, err := ed25519.GenerateKey(nil)
	if err != nil {
		t.Fatalf("GenerateKey: %v", err)
	}
	h := &registryHosting{
		t:         t,
		indexKey:  priv,
		indexFP:   blueprint.Fingerprint(pub),
		doc:       hubreg.Document{SchemaVersion: hubreg.CurrentIndexSchema},
		artifacts: map[string][]byte{},
	}
	mux := http.NewServeMux()
	mux.HandleFunc("/index.json", func(w http.ResponseWriter, _ *http.Request) {
		h.calls++
		signed, err := hubreg.Sign(h.doc, h.indexKey)
		if err != nil {
			http.Error(w, err.Error(), http.StatusInternalServerError)
			return
		}
		raw, err := json.Marshal(signed)
		if err != nil {
			http.Error(w, err.Error(), http.StatusInternalServerError)
			return
		}
		_, _ = w.Write(raw)
	})
	mux.HandleFunc("/artifacts/", func(w http.ResponseWriter, r *http.Request) {
		h.calls++
		body, ok := h.artifacts[r.URL.Path]
		if !ok {
			http.NotFound(w, r)
			return
		}
		_, _ = w.Write(body)
	})
	h.srv = httptest.NewServer(mux)
	t.Cleanup(h.srv.Close)
	return h
}

// publish runs the real publish→index path: build a submission from an
// artifact, fold it into the index, and serve the artifact bytes.
func (h *registryHosting) publish(raw []byte, opts hubreg.SubmissionOptions) hub.Entry {
	h.t.Helper()
	sub, err := hubreg.BuildSubmission(raw, opts)
	if err != nil {
		h.t.Fatalf("BuildSubmission: %v", err)
	}
	doc, _, err := hubreg.AddEntry(h.doc, sub)
	if err != nil {
		h.t.Fatalf("AddEntry: %v", err)
	}
	h.doc = doc
	h.artifacts[sub.Entry.ArtifactURL] = sub.Artifact
	return sub.Entry
}

func (h *registryHosting) revoke(rev hubreg.Revocation) {
	h.t.Helper()
	doc, _, err := hubreg.AddRevocation(h.doc, rev)
	if err != nil {
		h.t.Fatalf("AddRevocation: %v", err)
	}
	h.doc = doc
}

// client is the daemon's real hub client, wired exactly as cmd/vnproxd wires
// it when [hub] index_signers is set.
func (h *registryHosting) client(trusted []string) *hub.Client {
	h.t.Helper()
	c, err := hub.NewClient(h.srv.URL, hub.WithHTTPClient(hubreg.NewGate(nil, trusted)), hub.WithCacheTTL(0))
	if err != nil {
		h.t.Fatalf("hub.NewClient: %v", err)
	}
	return c
}

func mustMarshal(t *testing.T, v any) []byte {
	t.Helper()
	raw, err := json.Marshal(v)
	if err != nil {
		t.Fatalf("marshal: %v", err)
	}
	return raw
}

// TestHubRegistry_UntrustedArtifactKeyRefused_TrustedInstalls is AC2, through
// the real install path: two blueprints published to one real signed index,
// one signed by a key this installation trusts and one by a key it does not.
// Only the trusted one installs; the untrusted one is refused *and saved
// nowhere*.
func TestHubRegistry_UntrustedArtifactKeyRefused_TrustedInstalls(t *testing.T) {
	svc := newBlueprintTestService(t, "pve1")
	trust := blueprint.NewTrustStore(t.TempDir())
	audit := &fakeAuditor{}

	_, trustedKey, _ := ed25519.GenerateKey(nil)
	_, untrustedKey, _ := ed25519.GenerateKey(nil)

	host := newRegistryHosting(t)
	goodBundle, err := blueprint.SignBundle(testBlueprint("hub-good"), trustedKey)
	if err != nil {
		t.Fatalf("SignBundle: %v", err)
	}
	badBundle, err := blueprint.SignBundle(testBlueprint("hub-bad"), untrustedKey)
	if err != nil {
		t.Fatalf("SignBundle: %v", err)
	}
	good := host.publish(mustMarshal(t, goodBundle), hubreg.SubmissionOptions{Type: hub.TypeBlueprint, Version: "1.0.0"})
	host.publish(mustMarshal(t, badBundle), hubreg.SubmissionOptions{Type: hub.TypeBlueprint, Version: "1.0.0"})

	// This installation trusts exactly one of the two publisher keys.
	if err := trust.Add(blueprint.TrustedSigner{
		Fingerprint: good.Signature.PublicKeyFingerprint,
		PublicKey:   good.Signature.PublicKey,
	}); err != nil {
		t.Fatalf("trust.Add: %v", err)
	}

	auth := blueprintTestAuth(map[string]bool{"netRead": true, "netWrite": true})
	r := newHubTestRouter(t, host.client([]string{host.indexFP}), nil, svc, trust, nil, audit, auth)

	// The trusted artifact installs.
	rec := do(t, r, http.MethodPost, "/api/v1/hub/install", map[string]any{"type": "blueprint", "id": "hub-good", "version": "1.0.0"})
	if rec.Code != http.StatusCreated {
		t.Fatalf("trusted install status = %d, want 201: %s", rec.Code, rec.Body.String())
	}
	var okResp hubInstallResponse
	if err := json.Unmarshal(rec.Body.Bytes(), &okResp); err != nil {
		t.Fatalf("decode: %v", err)
	}
	if okResp.Status != bundleStatusImported || okResp.Blueprint == nil {
		t.Fatalf("status = %q blueprint = %v, want an import", okResp.Status, okResp.Blueprint)
	}

	// The untrusted-signer artifact is refused — no import, no implicit trust.
	rec = do(t, r, http.MethodPost, "/api/v1/hub/install", map[string]any{"type": "blueprint", "id": "hub-bad", "version": "1.0.0"})
	if rec.Code != http.StatusOK {
		t.Fatalf("untrusted install status = %d, want 200 with a gate verdict: %s", rec.Code, rec.Body.String())
	}
	var badResp hubInstallResponse
	if err := json.Unmarshal(rec.Body.Bytes(), &badResp); err != nil {
		t.Fatalf("decode: %v", err)
	}
	if badResp.Status != bundleStatusUntrustedSignature {
		t.Fatalf("status = %q, want %q", badResp.Status, bundleStatusUntrustedSignature)
	}
	if badResp.Blueprint != nil {
		t.Fatal("a refused install returned a blueprint")
	}
	// It really did not land in the store.
	if _, getErr := svc.Get(t.Context(), "hub-bad"); getErr == nil {
		t.Fatal("the untrusted-signer blueprint was saved anyway")
	}
	// And the refusal is auditable — a hub blueprint install audits through
	// T-1107's own import path ("blueprint.import"), because it *is* that
	// path; the hub adds no second audit vocabulary.
	var denied bool
	for _, e := range audit.entries {
		if e.Action == "blueprint.import" && e.Result == "denied" {
			denied = true
		}
	}
	if !denied {
		t.Fatalf("the refused install wrote no denial audit row (rows: %+v)", audit.entries)
	}
}

// TestHubRegistry_TamperedArtifactRefused: the index is signed, but that says
// nothing about the artifact. An artifact edited after signing is still caught
// by T-1107's own verification — the index signature never substitutes for it.
func TestHubRegistry_TamperedArtifactRefused(t *testing.T) {
	svc := newBlueprintTestService(t, "pve1")
	trust := blueprint.NewTrustStore(t.TempDir())

	_, key, _ := ed25519.GenerateKey(nil)
	host := newRegistryHosting(t)
	signed, err := blueprint.SignBundle(testBlueprint("hub-tampered"), key)
	if err != nil {
		t.Fatalf("SignBundle: %v", err)
	}
	entry := host.publish(mustMarshal(t, signed), hubreg.SubmissionOptions{Type: hub.TypeBlueprint, Version: "1.0.0"})
	if err := trust.Add(blueprint.TrustedSigner{Fingerprint: entry.Signature.PublicKeyFingerprint, PublicKey: entry.Signature.PublicKey}); err != nil {
		t.Fatalf("trust.Add: %v", err)
	}
	// Swap the hosted artifact bytes for an edited bundle (the index still
	// verifies — only the artifact was touched).
	tampered := signed
	tampered.Blueprint.Name = "malicious edit"
	host.artifacts[entry.ArtifactURL] = mustMarshal(t, tampered)

	auth := blueprintTestAuth(map[string]bool{"netRead": true, "netWrite": true})
	r := newHubTestRouter(t, host.client([]string{host.indexFP}), nil, svc, trust, nil, &fakeAuditor{}, auth)

	rec := do(t, r, http.MethodPost, "/api/v1/hub/install", map[string]any{"type": "blueprint", "id": "hub-tampered", "version": "1.0.0"})
	var resp hubInstallResponse
	if err := json.Unmarshal(rec.Body.Bytes(), &resp); err != nil {
		t.Fatalf("decode: %v", err)
	}
	if resp.Status != bundleStatusInvalidSignature {
		t.Fatalf("status = %q, want %q", resp.Status, bundleStatusInvalidSignature)
	}
}

// TestHubRegistry_RevokedArtifactRefusedOffline is AC3 at the daemon's
// boundary: after revocation the entry is not offered by GET /hub/index, an
// install of it 404s, and the refusal costs no extra network request beyond
// the index fetch the client already made.
func TestHubRegistry_RevokedArtifactRefusedOffline(t *testing.T) {
	svc := newBlueprintTestService(t, "pve1")
	trust := blueprint.NewTrustStore(t.TempDir())

	_, key, _ := ed25519.GenerateKey(nil)
	host := newRegistryHosting(t)
	signed, err := blueprint.SignBundle(testBlueprint("hub-bad-actor"), key)
	if err != nil {
		t.Fatalf("SignBundle: %v", err)
	}
	entry := host.publish(mustMarshal(t, signed), hubreg.SubmissionOptions{Type: hub.TypeBlueprint, Version: "1.0.0"})
	if err := trust.Add(blueprint.TrustedSigner{Fingerprint: entry.Signature.PublicKeyFingerprint, PublicKey: entry.Signature.PublicKey}); err != nil {
		t.Fatalf("trust.Add: %v", err)
	}

	client := host.client([]string{host.indexFP})
	auth := blueprintTestAuth(map[string]bool{"netRead": true, "netWrite": true})
	r := newHubTestRouter(t, client, nil, svc, trust, nil, &fakeAuditor{}, auth)

	// Before revocation it is offered and installable — the control that
	// proves the refusal below is the revocation, not a broken fixture.
	rec := do(t, r, http.MethodGet, "/api/v1/hub/index", nil)
	var idxResp hubIndexResponse
	if err := json.Unmarshal(rec.Body.Bytes(), &idxResp); err != nil {
		t.Fatalf("decode: %v", err)
	}
	if len(idxResp.Items) != 1 {
		t.Fatalf("items = %d, want 1 before revocation", len(idxResp.Items))
	}

	host.revoke(hubreg.Revocation{Type: hub.TypeBlueprint, ID: "hub-bad-actor", Reason: "publisher account compromised", At: 1})

	rec = do(t, r, http.MethodGet, "/api/v1/hub/index", nil)
	idxResp = hubIndexResponse{}
	if err := json.Unmarshal(rec.Body.Bytes(), &idxResp); err != nil {
		t.Fatalf("decode: %v", err)
	}
	if len(idxResp.Items) != 0 {
		t.Fatalf("items = %+v, want none after revocation", idxResp.Items)
	}
	rec = do(t, r, http.MethodPost, "/api/v1/hub/install", map[string]any{"type": "blueprint", "id": "hub-bad-actor", "version": "1.0.0"})
	if rec.Code != http.StatusNotFound {
		t.Fatalf("install of a revoked artifact status = %d, want 404: %s", rec.Code, rec.Body.String())
	}
	if _, getErr := svc.Get(t.Context(), "hub-bad-actor"); getErr == nil {
		t.Fatal("a revoked blueprint was installed")
	}

	// The offline half: with the index already fetched and the hosting taken
	// away entirely, the revoked artifact is still refused (from the cached
	// signed document) while a *live* artifact fetch fails with a network
	// error — proving the refusal is not just "everything fails now".
	fresh := host.client([]string{host.indexFP})
	if _, err := fresh.Index(t.Context()); err != nil {
		t.Fatalf("Index: %v", err)
	}
	host.srv.Close()
	if _, err := fresh.FetchBlueprintBundle(t.Context(), entry); !errors.Is(err, hubreg.ErrRevoked) {
		t.Fatalf("err = %v, want ErrRevoked with the registry offline", err)
	}
	live := hub.Entry{Type: hub.TypeBlueprint, ID: "other", Version: "1.0.0", ArtifactURL: "/artifacts/blueprint/other/1.0.0.json"}
	if _, err := fresh.FetchBlueprintBundle(t.Context(), live); errors.Is(err, hubreg.ErrRevoked) {
		t.Fatalf("a non-revoked fetch reported ErrRevoked: %v", err)
	}
}

// TestHubRegistry_CorruptIndexYieldsNoCatalog is AC5 at the daemon's boundary:
// a corrupted index is a 502 with an empty catalog, never a partial one.
func TestHubRegistry_CorruptIndexYieldsNoCatalog(t *testing.T) {
	_, key, _ := ed25519.GenerateKey(nil)
	host := newRegistryHosting(t)
	signed, err := blueprint.SignBundle(testBlueprint("bp-a"), key)
	if err != nil {
		t.Fatalf("SignBundle: %v", err)
	}
	host.publish(mustMarshal(t, signed), hubreg.SubmissionOptions{Type: hub.TypeBlueprint, Version: "1.0.0"})

	auth := blueprintTestAuth(map[string]bool{"netRead": true, "netWrite": true})

	// Pinned to a signer that did not sign this index — the client-visible
	// symptom of any index that fails verification.
	otherPub, _, _ := ed25519.GenerateKey(nil)
	r := newHubTestRouter(t, host.client([]string{blueprint.Fingerprint(otherPub)}), nil, nil, nil, nil, &fakeAuditor{}, auth)

	rec := do(t, r, http.MethodGet, "/api/v1/hub/index", nil)
	if rec.Code != http.StatusBadGateway {
		t.Fatalf("status = %d, want 502: %s", rec.Code, rec.Body.String())
	}
	var body map[string]any
	if err := json.Unmarshal(rec.Body.Bytes(), &body); err != nil {
		t.Fatalf("decode: %v", err)
	}
	if _, hasItems := body["items"]; hasItems {
		t.Fatalf("a failed index verification returned a catalog: %s", rec.Body.String())
	}
}
