package certs

import (
	"fmt"
	"sort"
	"strings"
	"time"
)

// Check names. These cross the API boundary and appear in findings, so they
// are part of the contract once shipped.
const (
	CheckExpired      = "cert_expired"
	CheckExpiring     = "cert_expiring"
	CheckSANMismatch  = "cert_san_mismatch"
	CheckNotChained   = "cert_not_chained"
	CheckCAMismatch   = "cert_ca_mismatch"
	CheckWeakKey      = "cert_weak_key"
	CheckMissing      = "cert_missing"
	CheckUnreadable   = "cert_unreadable"
	SeverityError     = "error"
	SeverityWarning   = "warning"
	DefaultExpiryWarn = 30 * 24 * time.Hour
)

// Minimum key strengths. RSA-2048 is what PVE itself issues; anything below
// is a certificate somebody generated by hand years ago. The ECDSA floor is
// P-256.
const (
	minRSABits   = 2048
	minECDSABits = 256
)

// Issue is one problem found with one certificate.
//
// Remediation is a required field, not an optional nicety. Every issue here is
// detection-only — vnprox does not renew or reissue certificates (see
// planning/tasks/phase-23.md's scope note) — so an issue without the command
// that fixes it would leave the operator exactly where they started.
type Issue struct {
	Check       string `json:"check"`
	Severity    string `json:"severity"`
	Node        string `json:"node,omitempty"`
	Path        string `json:"path,omitempty"`
	Detail      string `json:"detail"`
	Remediation string `json:"remediation"`
}

// Report is an inventory plus everything wrong with it.
type Report struct {
	Inventory Inventory `json:"inventory"`
	Issues    []Issue   `json:"issues"`
}

// ClusterFacts is what the checks need to know about the cluster that the
// certificates themselves cannot tell them: who the members are, and what
// address vnprox would dial each one at.
//
// Supplied by the caller rather than discovered here, because "the address a
// peer is dialled at" is internal/peer's decision (peer.Client.Peers), and a
// second, independently-derived answer to that question is precisely how a
// check ends up validating something other than what actually happens.
type ClusterFacts struct {
	// DialAddrs maps node name to the host part of the address the peer
	// client would dial. Empty for a single-node cluster.
	DialAddrs map[string]string
	// Members is every node PVE reports as a cluster member, including this
	// one. Empty means "unknown" — the cert_missing check then has no
	// authority to say a node's certificate is absent and stays silent.
	Members []string
}

// Evaluate runs every check against inv.
//
// expiryWarn is how far ahead cert_expiring looks; zero means
// DefaultExpiryWarn. verifyChain is injected so tests can exercise the
// chained/not-chained branches without a real CA on disk, and so the
// production path can re-read the CA from the same root the scan used.
func Evaluate(inv Inventory, facts ClusterFacts, now time.Time, expiryWarn time.Duration, verifyChain func(leafPath string) error) []Issue {
	if expiryWarn <= 0 {
		expiryWarn = DefaultExpiryWarn
	}
	var issues []Issue

	for _, cert := range inv.Certificates {
		issues = append(issues, expiryIssues(cert, now, expiryWarn)...)
		issues = append(issues, weakKeyIssues(cert)...)
		issues = append(issues, chainIssues(cert, inv, verifyChain)...)
		issues = append(issues, sanIssues(cert, facts)...)
	}

	issues = append(issues, missingIssues(inv, facts)...)
	issues = append(issues, unreadableIssues(inv)...)

	sortIssues(issues)
	return issues
}

func expiryIssues(cert Certificate, now time.Time, warn time.Duration) []Issue {
	left := cert.ExpiresIn(now)
	switch {
	case left <= 0:
		return []Issue{{
			Check:    CheckExpired,
			Severity: SeverityError,
			Node:     cert.Node,
			Path:     cert.Path,
			Detail: fmt.Sprintf("%s expired on %s (%s ago)",
				describe(cert), cert.NotAfter.Format(time.RFC3339), roundDuration(-left)),
			Remediation: renewCommand(cert),
		}}
	case left <= warn:
		return []Issue{{
			Check:    CheckExpiring,
			Severity: SeverityWarning,
			Node:     cert.Node,
			Path:     cert.Path,
			Detail: fmt.Sprintf("%s expires on %s, in %s",
				describe(cert), cert.NotAfter.Format(time.RFC3339), roundDuration(left)),
			Remediation: renewCommand(cert),
		}}
	}
	return nil
}

func weakKeyIssues(cert Certificate) []Issue {
	var reasons []string
	switch cert.KeyAlgorithm {
	case "RSA":
		if cert.KeyBits > 0 && cert.KeyBits < minRSABits {
			reasons = append(reasons, fmt.Sprintf("a %d-bit RSA key (minimum %d)", cert.KeyBits, minRSABits))
		}
	case "ECDSA":
		if cert.KeyBits > 0 && cert.KeyBits < minECDSABits {
			reasons = append(reasons, fmt.Sprintf("a %d-bit ECDSA key (minimum %d)", cert.KeyBits, minECDSABits))
		}
	}
	if strings.Contains(strings.ToUpper(cert.SignatureAlgorithm), "SHA1") ||
		strings.Contains(strings.ToUpper(cert.SignatureAlgorithm), "MD5") {
		reasons = append(reasons, fmt.Sprintf("a %s signature", cert.SignatureAlgorithm))
	}
	if len(reasons) == 0 {
		return nil
	}
	return []Issue{{
		Check:       CheckWeakKey,
		Severity:    SeverityWarning,
		Node:        cert.Node,
		Path:        cert.Path,
		Detail:      fmt.Sprintf("%s uses %s", describe(cert), strings.Join(reasons, " and ")),
		Remediation: renewCommand(cert),
	}}
}

// chainIssues covers the two distinct ways a node leaf can fail to belong to
// the cluster's CA, kept separate because they mean different things:
//
//   - cert_ca_mismatch: the issuer name does not match the cluster CA at all.
//     Almost always a half-completed `pvecm updatecerts` — the CA was
//     regenerated and this node's leaf was not reissued. Diagnosable from the
//     names alone, which is why it is checked first and reported specifically.
//   - cert_not_chained: the issuer name matches but cryptographic verification
//     fails (a leaf issued by an *older* CA with the same subject, or a
//     corrupted file). Strictly worse to diagnose, so it gets its own name.
func chainIssues(cert Certificate, inv Inventory, verifyChain func(string) error) []Issue {
	if !cert.expectsClusterCA() || inv.ClusterCA == nil {
		return nil
	}
	if cert.Issuer != inv.ClusterCA.Subject {
		return []Issue{{
			Check:    CheckCAMismatch,
			Severity: SeverityError,
			Node:     cert.Node,
			Path:     cert.Path,
			Detail: fmt.Sprintf("%s was issued by %q, but this cluster's CA is %q — peer TLS pins the cluster CA, so this node cannot be verified by its peers",
				describe(cert), cert.Issuer, inv.ClusterCA.Subject),
			Remediation: fmt.Sprintf("on %s: pvecm updatecerts -f", nodeOrThisNode(cert.Node)),
		}}
	}
	if verifyChain == nil {
		return nil
	}
	if err := verifyChain(cert.Path); err != nil {
		return []Issue{{
			Check:    CheckNotChained,
			Severity: SeverityError,
			Node:     cert.Node,
			Path:     cert.Path,
			Detail: fmt.Sprintf("%s does not verify against the cluster CA: %v — peer TLS pins that CA, so this node cannot be verified by its peers",
				describe(cert), err),
			Remediation: fmt.Sprintf("on %s: pvecm updatecerts -f", nodeOrThisNode(cert.Node)),
		}}
	}
	return nil
}

// sanIssues is T-1906-bug-01's check: does this node's certificate actually
// authenticate the identity a peer would verify it as?
//
// Both candidate identities are accepted, because internal/peer now dials by
// IP but verifies against the node name where the certificate covers it (see
// peername.go). The certificate is only a problem when it covers *neither* —
// at which point pinned verification fails closed and the node drops out of
// the cluster's peer mesh.
func sanIssues(cert Certificate, facts ClusterFacts) []Issue {
	if cert.Kind != KindNodeLeaf || cert.Node == "" {
		return nil
	}
	addr := facts.DialAddrs[cert.Node]
	if addr == "" {
		// No address known for this node — a single-node cluster, or a node
		// PVE did not report an address for. Saying a certificate fails to
		// cover an address we cannot name would be an unfalsifiable claim.
		return nil
	}
	if cert.Covers(cert.Node) || cert.Covers(addr) {
		return nil
	}
	return []Issue{{
		Check:    CheckSANMismatch,
		Severity: SeverityError,
		Node:     cert.Node,
		Path:     cert.Path,
		Detail: fmt.Sprintf("%s covers %s, which includes neither this node's peer address (%s) nor its node name (%s) — pinned peer TLS verifies one of those, so every peer connection to this node fails closed",
			describe(cert), sanSummary(cert), addr, cert.Node),
		Remediation: fmt.Sprintf("on %s: pvecm updatecerts -f (regenerates the node certificate with its current addresses), then systemctl restart pveproxy vnprox", cert.Node),
	}}
}

func missingIssues(inv Inventory, facts ClusterFacts) []Issue {
	if len(facts.Members) == 0 {
		return nil
	}
	var out []Issue
	for _, node := range facts.Members {
		if _, ok := inv.LeafFor(node); ok {
			continue
		}
		out = append(out, Issue{
			Check:    CheckMissing,
			Severity: SeverityWarning,
			Node:     node,
			Detail: fmt.Sprintf("cluster member %s has no certificate at %s/%s/%s — peers cannot verify it and it cannot verify them",
				node, nodesDir, node, nodeLeafName),
			Remediation: fmt.Sprintf("on %s: pvecm updatecerts -f", node),
		})
	}
	return out
}

func unreadableIssues(inv Inventory) []Issue {
	var out []Issue
	for _, fe := range inv.Errors {
		// A missing optional custom certificate is not an issue; Scan already
		// filters those, so anything reaching here is a real read failure.
		out = append(out, Issue{
			Check:       CheckUnreadable,
			Severity:    SeverityWarning,
			Node:        fe.Node,
			Path:        fe.Path,
			Detail:      fmt.Sprintf("could not read %s: %s", fe.Path, fe.Error),
			Remediation: "check that /etc/pve is mounted (systemctl status pve-cluster) and that vnproxd can read it",
		})
	}
	return out
}

func describe(cert Certificate) string {
	switch cert.Kind {
	case KindClusterCA:
		return "the cluster CA"
	case KindNodeLeaf:
		return fmt.Sprintf("node %s's certificate", cert.Node)
	case KindCustom:
		return fmt.Sprintf("node %s's custom (pveproxy) certificate", cert.Node)
	case KindDaemon:
		return "the certificate vnproxd is serving"
	default:
		return cert.Path
	}
}

// sanSummary renders a SAN list compactly for a one-line finding detail.
func sanSummary(cert Certificate) string {
	if len(cert.SANs) == 0 {
		return "no subject alternative names"
	}
	parts := make([]string, 0, len(cert.SANs))
	for _, s := range cert.SANs {
		parts = append(parts, s.Value)
	}
	return strings.Join(parts, ", ")
}

// renewCommand names the command that actually reissues this certificate.
// The cluster CA and a custom/ACME certificate are renewed differently from a
// node leaf, and telling an operator to run `pvecm updatecerts` at a custom
// certificate would be actively wrong — it does not touch pveproxy-ssl.pem.
func renewCommand(cert Certificate) string {
	switch cert.Kind {
	case KindClusterCA:
		return "regenerating the cluster CA reissues every node certificate and is a cluster-wide operation — see the Proxmox VE documentation for `pvecm updatecerts` before starting"
	case KindCustom:
		return fmt.Sprintf("on %s: pvenode acme cert order (ACME), or replace the certificate with `pvenode cert set`", nodeOrThisNode(cert.Node))
	case KindDaemon:
		return "replace the certificate at server.tls_cert in /etc/vnprox/config.toml, then: systemctl reload vnprox"
	default:
		return fmt.Sprintf("on %s: pvecm updatecerts -f, then: systemctl restart pveproxy", nodeOrThisNode(cert.Node))
	}
}

func nodeOrThisNode(node string) string {
	if node == "" {
		return "the node"
	}
	return node
}

// roundDuration renders a duration the way an operator thinks about
// certificate lifetimes: days, or hours when less than a day remains.
func roundDuration(d time.Duration) string {
	if d < 0 {
		d = -d
	}
	if d >= 24*time.Hour {
		days := int(d.Hours() / 24)
		if days == 1 {
			return "1 day"
		}
		return fmt.Sprintf("%d days", days)
	}
	hours := int(d.Hours())
	if hours <= 1 {
		return "under an hour"
	}
	return fmt.Sprintf("%d hours", hours)
}

// sortIssues gives a deterministic order: errors before warnings, then by
// node, check, and path.
func sortIssues(issues []Issue) {
	rank := map[string]int{SeverityError: 0, SeverityWarning: 1}
	sort.SliceStable(issues, func(i, j int) bool {
		a, b := issues[i], issues[j]
		if rank[a.Severity] != rank[b.Severity] {
			return rank[a.Severity] < rank[b.Severity]
		}
		if a.Node != b.Node {
			return a.Node < b.Node
		}
		if a.Check != b.Check {
			return a.Check < b.Check
		}
		return a.Path < b.Path
	})
}
