// SPDX-License-Identifier: Apache-2.0

// completion.go implements `vnproxctl completion bash|zsh` (T-4011): shell
// completion for vnproxctl's subcommands, generated from commandTable
// (main.go) — the exact table `run` dispatches through — rather than a
// second, hand-maintained list of command names. A subcommand added to
// commandTable is completable the moment it is dispatchable; nothing here
// needs editing to pick it up, which is the whole point (a hand-maintained
// completion script is the thing this file exists to avoid).
//
// Completion is two-level: the top-level command name, and (for commands
// with subcommands, e.g. `snapshots list|restore`) the leaf verb after it.
// Per-flag completion is intentionally out of scope — each subcommand's
// flag.FlagSet is registered privately inside its own run* function, and
// reaching into thirty-odd private flag sets to build a fully positional,
// per-command flag completion table is a materially larger undertaking
// than this card's shell-completion deliverable calls for. Instead every
// command offers the same flat set of long flags this binary's commands
// actually share (commonCompletionFlags below) — genuinely useful for
// `--` completion without claiming a precision this file does not have.
package main

import (
	"fmt"
	"io"
	"sort"
	"strings"
)

// commonCompletionFlags is the union of long flags most vnproxctl
// subcommands accept (see main.go's printUsage flag sections). Offered as
// completions for any command's `-`-prefixed word; an individual
// subcommand's own `-h` remains the authority on which of these it actually
// takes.
var commonCompletionFlags = []string{
	"--config", "--url", "--token", "--insecure", "--timeout", "--out",
	"--out-dir", "--node", "--limit", "-o",
}

func runCompletion(args []string, stdout, stderr io.Writer) int {
	if len(args) != 1 {
		_, _ = fmt.Fprintln(stderr, "vnproxctl completion: expected exactly one shell name (bash or zsh)")
		return ExitUsage
	}
	switch args[0] {
	case "bash":
		_, _ = io.WriteString(stdout, bashCompletionScript())
		return ExitSuccess
	case "zsh":
		_, _ = io.WriteString(stdout, zshCompletionScript())
		return ExitSuccess
	default:
		_, _ = fmt.Fprintf(stderr, "vnproxctl completion: unknown shell %q (want bash or zsh)\n", args[0])
		return ExitUsage
	}
}

// topLevelCommandNames returns commandTable's command names, plus the two
// commands run's own switch handles outside the table (completion itself,
// and help — --version and -h/--help/help are omitted from completion
// offers deliberately: they are rarely what <TAB> is for), sorted so the
// generated script's word list is stable across regenerations.
func topLevelCommandNames() []string {
	names := make([]string, 0, len(commandTable)+1)
	for _, c := range commandTable {
		names = append(names, c.name)
	}
	names = append(names, "completion")
	sort.Strings(names)
	return names
}

// bashCompletionScript renders a `complete -F` function: word 1 completes a
// top-level command name; word 2, for a command commandTable declares
// subcommands for, completes one of those; every other word completes
// commonCompletionFlags. Sourceable directly (`source
// <(vnproxctl completion bash)`) or installable under
// /etc/bash_completion.d/vnproxctl.
func bashCompletionScript() string {
	var b strings.Builder
	b.WriteString("# vnproxctl bash completion — generated by `vnproxctl completion bash`.\n")
	b.WriteString("# Source it: source <(vnproxctl completion bash)\n")
	b.WriteString("_vnproxctl() {\n")
	b.WriteString("  local cur prev words cword\n")
	b.WriteString("  COMPREPLY=()\n")
	b.WriteString("  cur=\"${COMP_WORDS[COMP_CWORD]}\"\n")
	fmt.Fprintf(&b, "  local commands=\"%s\"\n", strings.Join(topLevelCommandNames(), " "))
	fmt.Fprintf(&b, "  local flags=\"%s\"\n", strings.Join(commonCompletionFlags, " "))
	b.WriteString("  if [ \"$COMP_CWORD\" -eq 1 ]; then\n")
	b.WriteString("    COMPREPLY=( $(compgen -W \"$commands\" -- \"$cur\") )\n")
	b.WriteString("    return 0\n")
	b.WriteString("  fi\n")
	b.WriteString("  case \"${COMP_WORDS[1]}\" in\n")
	for _, c := range commandTable {
		if len(c.subcommands) == 0 {
			continue
		}
		fmt.Fprintf(&b, "    %s)\n", c.name)
		b.WriteString("      if [ \"$COMP_CWORD\" -eq 2 ]; then\n")
		fmt.Fprintf(&b, "        COMPREPLY=( $(compgen -W \"%s\" -- \"$cur\") )\n", strings.Join(c.subcommands, " "))
		b.WriteString("        return 0\n")
		b.WriteString("      fi\n")
		b.WriteString("      ;;\n")
	}
	b.WriteString("  esac\n")
	b.WriteString("  if [[ \"$cur\" == -* ]]; then\n")
	b.WriteString("    COMPREPLY=( $(compgen -W \"$flags\" -- \"$cur\") )\n")
	b.WriteString("  fi\n")
	b.WriteString("}\n")
	b.WriteString("complete -F _vnproxctl vnproxctl\n")
	return b.String()
}

// zshCompletionScript renders a `#compdef` function using zsh's bashcompinit
// bridge so it shares bashCompletionScript's exact word lists (one source
// of truth for both shells, not two scripts that can drift from each
// other).
func zshCompletionScript() string {
	var b strings.Builder
	b.WriteString("#compdef vnproxctl\n")
	b.WriteString("# vnproxctl zsh completion — generated by `vnproxctl completion zsh`.\n")
	b.WriteString("# Source it: source <(vnproxctl completion zsh)\n")
	b.WriteString("autoload -Uz bashcompinit && bashcompinit\n")
	b.WriteString(bashCompletionScript())
	return b.String()
}
